spring:
  profiles :
    active : qa
---
spring:
  profiles : dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/restapi
    password: Mysql@2022
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to my page!!

---
spring:
  profiles : qa
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/restapi-qa
    password: Mysql@2022
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to my page!!
---
spring:
  profiles : prod
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/restapi-prod
    password: Mysql@2022
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to my page!!
